crkn-rcdr/sapindale

- src/components/Nav.svelte
- src/routes/_layout.svelte
- src/routes/collection.svelte
- src/routes/deposit.svelte
- src/routes/index.svelte
Doesn't actually solve auth, yet, but I want to commit this to master.
> Re-organizes nav

- src/auth.js
- src/components/Nav.svelte
> Svlt sap div

- src/auth.js
- src/components/TypeAhead.svelte
- src/routes/_layout.svelte
- src/routes/deposit.svelte
- src/routes/index.svelte
This PR has a few general fixes for Sapindale, as well as the first pass at the TypeAhead component, which will be used to look up IDs in Couch databases for operating on documents.
> Typeahead document picker, phase 1

- src/components/BulkLookup.svelte
- src/components/TypeAhead.svelte
- src/couch.js
- src/routes/deposit.svelte
- src/styles/base.css
Have the POST call working
For the given list of Id's the POST works up on submit, Feedback requested for the approach
*Need to give out a generic naming convention, upon feedback
Check the styling and alignment as a final to do.
> Task-81 BulkId Fetch from dipstaging

- src/cantaloupe.js
- src/components/CanvasEditor.svelte
- src/components/CanvasThumbnail.svelte
- src/components/SortableList.svelte
- src/couch.js
- src/routes/_layout.svelte
- src/routes/accessLink/accessCollection.svelte
- src/routes/accessLink/accessManifest.svelte
- src/routes/accessLink/utilities.svelte
- src/routes/index.svelte
- src/routes/manifest/[id].svelte
- src/styles/base.css
- static/canadiana-logo.svg
- tailwind.config.js
Task 91; Able to load the Canvas images from Upholstery, revamp of couchJS functions.
> Loading cantaloupe data from upholstery

- src/components/CouchView.svelte
- src/routes/accessLink/utilities.svelte
> couchview: make output "Key" into a link

- src/components/CouchView.svelte
- src/routes/couchview/[db]/[ddoc]/[v].svelte
I'm looking for feedback from the Svelte/Javascript experts on this before merging with master.
> Handle numeric, string and json structure types #39

- src/components/FindDuplicates.svelte
- src/routes/findduplicates.svelte
> Find Duplicates

- src/components/Internalmeta.svelte
- src/couch.js
- src/couch/internalmeta.js
- src/routes/internalmeta.svelte
* Functionality of legacy collection manager #47
* if requested, functionality of 'internalmeta' csv from wipFindMoveCreate
> Tool to manage internalmeta data

- package.json
- src/components/Repository.svelte
- src/couch.js
- src/couch/repository.js
- src/routes/repository.svelte
- yarn.lock
This intends to replace validation statistics #48
> Repository related statistics

- Dockerfile
- package.json
- src/api.js
- src/api/collection.js
- src/api/slug.js
- src/components/CollectionSlug.svelte
- src/components/TextValueEditor.svelte
- src/couch.js
- src/routes/collection/[slug].svelte
- src/routes/index.svelte
- src/spinner.svelte
- src/styles/mvp.css
- webpack.config.js
- yarn.lock
There is still the icon that will have to be changed to green, i haven't found one yet.
> Half cooked, slug resolver retrieves the searched slug from db

- src/components/Packaging.svelte
The fix is so small I intend to merge right away.
> Incorrect element ID, failure to find ID meant failure to send request.

- src/components/Internalmeta.svelte
- src/routes/_layout.svelte
https://trello.com/c/HPymoBGC/182-internalmeta-legend-for-capcollections-tags
> CAP Collection Legend

- src/routes/index.svelte
We got approval from Beth on Friday to remove the student demo links.
> Remove student demos from index.

- src/components/ArchivalManifest.svelte
Potential solution to #77
We might want to have this limit apply across all views, and not only the status view.  We can discuss in this PR.
> Using limit to avoid problem with large lists and SlugResolver

- src/components/ArchivalManifest.svelte
Simple commit, shouldn't require much review.
> Added button to silence smelter status.  Should resolve #80

- src/components/CollectionEditor.svelte
Displaying parents, and some look and feel changes.
> Collection parent noid

- src/components/Couch/View.svelte
- src/routes/couchview/[db]/[ddoc]/[v].svelte
A PR to discuss possible fixes for #109
> CouchView parameter issue.

- src/components/Index/SlugSelector.svelte
- src/components/Slug/Resolver.svelte
- src/components/Slug/TypeAhead.svelte
- src/models/slug.js
- src/routes/manifest/slug/[slug].json.js
- src/routes/manifest/slug/available/[slug].json.js
- src/routes/manifest/slug/search/[prefix].json.js
- src/routes/slug/[slug].json.js
- src/routes/slug/index.svelte
- src/routes/slug/search/[prefix].json.js
> Points slug resolution to the `access` database

- src/components/Slug/Resolver.svelte
- src/routes/slug/index.svelte
Also sorts out some smaller problems.
> Distinguishes null slug resolutions from unperformed ones

- Dockerfile.dev
- Dockerfile.prod
- deployimage.sh
- package-lock.json
- package.json
- src/routes/packaging.svelte
https://github.com/crkn-rcdr/sapindale/issues/138
> Remove update aip
